services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: controledb
      POSTGRES_USER: suelen
      POSTGRES_PASSWORD: minhasenha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U suelen -d controledb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend-dotnet
      dockerfile: backend-dotnet/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=controledb;Username=suelen;Password=minhasenha"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: